### ISSUE TITLE
Text encoding issue with 1998-2005 xml files

### ISSUE THREAD

**Issue by SamHames** [wragge/hansard-xml#2]
It looks like there's a text encoding problem with (I think only?) the 1998-2005 XML files. I've been doing [some experiments](https://github.com/SamHames/hyperreal/tree/main/examples/australian_federal_hansard) and noticed a lot of character noise for that time window.

For example, if you compare [the original](https://parlinfo.aph.gov.au/parlInfo/download/chamber/hansardr/2005-02-10/toc_unixml/3670-4.xml;fileType=text%2Fxml) with [this file in the repository](https://raw.githubusercontent.com/wragge/hansard-xml/master/hofreps/2005/2005-02-10_3670-4.xml ) you'll see that this:

```
<business.start>
<day.start>2005-02-10</day.start>
<para>—————</para>
<para>
<inline font-weight="bold">The SPEAKER (Hon. David Hawker)</inline>
took the chair at 9.00 a.m. and read prayers.
</para>
</business.start>
```

has become:
```
<business.start>
<day.start>2005-02-10</day.start>
<para>âââââ</para>
<para>
<inline font-weight="bold">The SPEAKER (Hon. David Hawker)</inline>
took the chair at 9.00 a.m. and read prayers.
</para>
</business.start>
```

I should be able to put together a PR to fix this once I wrap my head around your harvesting notebook.

**Comment by wragge** [comment]
Looks like requests is using the wrong encoding. Manually setting the encoding to `utf-8` seems to work:

```python
response.encoding = "utf-8"
```

Currently re-harvesting 1998 to 2005.

**Comment by wragge** [comment]
Ok, I've reharvested 1998-2005. Hopefully it's ok now.
